name: Ping Render Backend

on:
  schedule:
    - cron: "*/15 * * * *"   
  workflow_dispatch:      

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render backend
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://weather-service-iye3.onrender.com/api/v1/health
